// CHECK ON SEARCH
export const CHECK_ON_SEARCH = 'CHECK_ON_SEARCH';

// OTHER
export const FETCHING = 'FETCHING';

// PLAY MUSIC
export const PLAY_TRACK = 'PLAY_TRACK';
export const PAUSE_TRACK = 'PAUSE_TRACK';
export const NEXT_TRACK = 'NEXT_TRACK';
export const PREVIOUS_TRACK = 'PREVIOUS_TRACK';
export const CHANGE_PLAYBACK_TYPE = 'CHANGE_PLAYBACK_TYPE';
export const RESET_TRACK = 'RESET_TRACK';
export const SET_TRACK = 'SET_TRACK';


// USER
export const REGISTER = 'REGISTER';
export const GET_MESSAGE = 'GET_MESSAGE';
export const LOGIN = 'LOGIN';
export const GET_CURRENT_USER = 'GET_CURRENT_USER';
export const LIKE_AUDIO = 'LIKE_AUDIO';

//ALBUM
export const FIND_ALL_ALBUMS = 'FIND_ALL_ALBUMS';
export const GET_ALL_ALBUMS = 'GET_ALL_ALBUMS';
export const FIND_ALBUM_BY_ID = 'FIND_ALBUM_BY_ID';
export const GET_ALBUM_BY_ID = 'GET_ALBUM_BY_ID';
export const SET_PLAY_STAT = 'SET_PLAY_STAT';
export const SET_RESET_STAT = 'SET_RESET_STAT';
export const SEARCH_ALBUM_BY_NAME = 'SEARCH_ALBUM_BY_NAME';
export const GET_ALBUM_BY_NAME = 'GET_ALBUM_BY_NAME';

// CATEGORY 
export const FIND_ALL_CATEGOTY = 'FIND_ALL_CATEGORY';
export const GET_ALL_CATEGORY = 'GET_ALL_CATEGORY';
export const FIND_CATEGORY_BY_ID = 'FIND_CATEGORY_BY_ID';
export const GET_CATEGORY_BY_ID = 'GET_CATEGORY_BY_ID';

// AUDIO
export const SEARCH_AUDIO_BY_NAME = 'SEARCH_AUDIO_BY_NAME';
export const GET_AUDIO_BY_NAME = 'GET_AUDIO_BY_NAME';
export const SEARCH_AUDIO_PAGING = 'SEARCH_AUDIO_PAGING';
export const GET_AUDIO_PAGING = 'GET_AUDIO_PAGING';
export const FIND_AUDIO_BY_ID = 'FIND_AUDIO_BY_ID';
export const GET_AUDIO_BY_ID = 'GET_AUDIO_BY_ID';
export const FIND_AUDIO_BY_ARTIST = 'FIND_AUDIO_BY_ARTIST';
export const GET_AUDIO_BY_ARTIST = 'GET_AUDIO_BY_ARTIST';
export const FIND_AUDIO_BY_CATEGORY_ARTIST = 'FIND_AUDIO_BY_CATEGORY_ARTIST';
export const GET_AUDIO_BY_CATEGORY_ARTIST = 'GET_AUDIO_BY_CATEGORY_ARTIST';
export const FIND_FAVORITE_CURRENT_USER = 'FIND_FAVORITE_CURRENT_USER';
export const GET_FAVORITE_AUDIO = 'GET_FAVORITE_AUDIO';
export const FIND_FAVORITE_AUDIO_PAGING = 'FIND_FAVORITE_AUDIO_PAGING';
export const GET_FAVORITE_AUDIO_PAGING = 'GET_FAVORITE_AUDIO_PAGING';

// ARTIST
export const SEARCH_ARTIST_BY_NAME = 'SEARCH_ARTIST_BY_NAME';
export const GET_SEARCH_ARTIST_BY_NAME = 'GET_SEARCH_ARTIST_BY_NAME';
export const SEARCH_ARTIST_BY_CATEGORY = 'SEARCH_ARTIST_BY_CATEGORY';
export const GET_SEARCH_ARTIST_BY_CATEGORY = 'GET_SEARCH_ARTIST_BY_CATEGORY';
export const FIND_ARTIST_BY_ID = 'FIND_ARTIST_BY_ID';
export const GET_ARTIST_BY_ID = 'GET_ARTIST_BY_ID';
export const FIND_ARTIST_BY_PLAYLIST = 'FIND_ARTIST_BY_PLAYLIST';
export const GET_ARTIST_BY_PLAYLIST = 'GET_ARTIST_BY_PLAYLIST';

//PLAYLIST
export const FIND_PLAYLIST_BY_NAME = 'FIND_PLAYLIST_BY_NAME';
export const GET_PLAYLIST_BY_NAME = 'GET_PLAYLIST_BY_NAME';
export const FIND_PLAYLIST_BY_ID = 'FIND_PLAYLIST_BY_ID';
export const GET_PLAYLIST_BY_ID = 'GET_PLAYLIST_BY_ID'; 
export const FIND_PLAYLIST_BY_USER_ID = 'FIND_PLAYLIST_BY_USER_ID';
export const GET_PLAYLIST_BY_USER_ID = 'GET_PLAYLIST_BY_USER_ID';
export const CREATE_PLAYLIST = 'CREATE_PLAYLIST';
export const GET_LATEST_PLAYLIST = 'GET_LATEST_PLAYLIST';
export const UPDATE_PLAYLIST = 'UPDATE_PLAYLIST';
export const INSERT_AUDIO_TO_PLAYLIST = 'INSERT_AUDIO_TO_PLAYLIST';
export const REMOVE_AUDIO_FROM_PLAYLIST = 'REMOVE_AUDIO_FROM_PLAYLIST';
export const DELETE_PLAYLIST_BY_ID = 'DELETE_PLAYLIST_BY_ID';
export const STORE_DAILY_MIX = 'STORE_DAILY_MIX';
export const FIND_PLAYLIST_BY_ID_ORDER_BY_AUDIO = 'FIND_PLAYLIST_BY_ID_ORDER_BY_AUDIO';
export const GET_PLAYLIST_BY_ID_ORDER_BY_AUDIO = 'GET_PLAYLIST_BY_ID_ORDER_BY_AUDIO';
