// CHECK ON SEARCH
export const CHECK_ON_SEARCH = 'CHECK_ON_SEARCH';



// USER
export const REGISTER = 'REGISTER';
export const GET_MESSAGE = 'GET_MESSAGE';
export const LOGIN = 'LOGIN';
export const GET_CURRENT_USER = 'GET_CURRENT_USER';


//ALBUM
export const FIND_ALL_ALBUMS = 'FIND_ALL_ALBUMS';
export const GET_ALL_ALBUMS = 'GET_ALL_ALBUMS';
export const FIND_ALBUM_BY_ID = 'FIND_ALBUM_BY_ID';
export const GET_ALBUM_BY_ID = 'GET_ALBUM_BY_ID';
export const SET_PLAY_STAT = 'SET_PLAY_STAT';
export const SET_RESET_STAT = 'SET_RESET_STAT';
export const SEARCH_ALBUM_BY_NAME = 'SEARCH_ALBUM_BY_NAME';
export const GET_ALBUM_BY_NAME = 'GET_ALBUM_BY_NAME';

// CATEGORY 
export const FIND_ALL_CATEGOTY = 'FIND_ALL_CATEGORY';
export const GET_ALL_CATEGORY = 'GET_ALL_CATEGORY';
export const FIND_CATEGORY_BY_ID = 'FIND_CATEGORY_BY_ID';
export const GET_CATEGORY_BY_ID = 'GET_CATEGORY_BY_ID';

// AUDIO
export const SEARCH_AUDIO_BY_NAME = 'SEARCH_AUDIO_BY_NAME';
export const GET_AUDIO_BY_NAME = 'GET_AUDIO_BY_NAME';

// ARTIST
export const SEARCH_ARTIST_BY_NAME = 'SEARCH_ARTIST_BY_NAME';
export const GET_SEARCH_ARTIST_BY_NAME = 'GET_SEARCH_ARTIST_BY_NAME';
export const SEARCH_ARTIST_BY_CATEGORY = 'SEARCH_ARTIST_BY_CATEGORY';
export const GET_SEARCH_ARTIST_BY_CATEGORY = 'GET_SEARCH_ARTIST_BY_CATEGORY';

//PLAYLIST
export const FIND_PLAYLIST_BY_NAME = 'FIND_PLAYLIST_BY_NAME';
export const GET_PLAYLIST_BY_NAME = 'GET_PLAYLIST_BY_NAME';
export const FIND_PLAYLIST_BY_ID = 'FIND_PLAYLIST_BY_ID';
export const GET_PLAYLIST_BY_ID = 'GET_PLAYLIST_BY_ID'; 
export const FIND_PLAYLIST_BY_USER_ID = 'FIND_PLAYLIST_BY_USER_ID';
export const GET_PLAYLIST_BY_USER_ID = 'GET_PLAYLIST_BY_USER_ID';
export const CREATE_PLAYLIST = 'CREATE_PLAYLIST';
export const GET_LATEST_PLAYLIST = 'GET_LATEST_PLAYLIST';
export const UPDATE_PLAYLIST = 'UPDATE_PLAYLIST';

